In [264]:
import json
from matplotlib import pyplot as plt
from collections import defaultdict
from sklearn import linear_model
import numpy
import random
import gzip
import math

In [265]:
def assertFloat(x): # Checks that an answer is a float
    assert type(float(x)) == float

def assertFloatList(items, N):
    assert len(items) == N
    assert [type(float(x)) for x in items] == [float]*N

In [266]:
f = gzip.open("young_adult_10000.json.gz")
dataset = []
for l in f:
    dataset.append(json.loads(l))

In [267]:
len(dataset)

10000

In [561]:
answers = {"Q1":[3.688533040832031, 0.07109019019954244, 1.5231747404538287],
           "Q2":[3.7175128077972013, 0.07527591733232629, -4.121506529487976e-05, 1.5214029246165832],
           "Q3":[1.5231747404538287, 1.5046686106250917, 1.496684551517923, 1.490447730223069, 1.4896106953961648],
           "Q4":[1.5248743859866292,1.4977199259322445,1.4856632190311088,1.4767337440080983,1.4809577272893133],
           "Q5":0.907,
           "Q6":[0, 20095, 0, 308, 0.5],
           "Q7":[88, 16332, 3763, 220, 0.4507731134255145],
           "Q8":[0.0, 0.0, 0.03, 0.033, 0.0308]} # Put your answers to each question in this dictionary

In [268]:
dataset[0]

{'user_id': '8842281e1d1347389f2ab93d60773d4d',
 'book_id': '2767052',
 'review_id': '248c011811e945eca861b5c31a549291',
 'rating': 5,
 'review_text': "I cracked and finally picked this up. Very enjoyable quick read - couldn't put it down - it was like crack. \n I'm a bit bothered by the lack of backstory of how Panem and the Hunger Games come about. It is just kind of explained away in a few paragraphs and we are left to accept this very strange world where teenagers are pitted into an arena each year to kill each other? I was expecting it because I've seen Battle Royale, but I would have appreciated knowing more of the backstory of how the world could have come into such a odd state. \n I suppose what makes a book like this interesting is thinking about the strategy of it all. The players are going to be statistically encouraged to band together because they will last longer that way, but by definition of course any partnership will be broken, and the drama of how that unfolds is alw

In [287]:
### Question 1

In [288]:
def feature(datum):
    # your implementation
    feat = datum['review_text'].count('!')
    return [feat]


In [289]:
X = [feature(data) for data in dataset]
Y = [data['rating'] for data in dataset]

In [290]:
print(X[:40])

[[0], [1], [0], [0], [0], [0], [4], [2], [1], [0], [0], [0], [0], [0], [0], [2], [0], [1], [1], [0], [0], [0], [0], [0], [0], [0], [1], [0], [0], [0], [0], [1], [0], [0], [0], [1], [1], [0], [7], [1]]


In [291]:
print(Y[0:40])

[5, 5, 4, 2, 5, 5, 5, 5, 5, 5, 4, 5, 2, 5, 4, 3, 3, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 5, 4, 4, 5, 5, 2, 5, 2, 5, 4]


In [292]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [293]:
lr.fit(X,Y)

LinearRegression()

In [294]:
lr.coef_

array([0.07109019])

In [295]:
lr.intercept_

3.688533040832031

In [300]:
[theta0,theta1]=lr.intercept_,lr.coef_[0]

In [301]:
Y_pred=lr.predict(X)
Y_pred[:10]

array([3.68853304, 3.75962323, 3.68853304, 3.68853304, 3.68853304,
       3.68853304, 3.9728938 , 3.83071342, 3.75962323, 3.68853304])

In [302]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y,Y_pred)
mse

1.5231747404538287

In [303]:
answers['Q1'] = [theta0, theta1, mse]
answers['Q1']

[3.688533040832031, 0.07109019019954244, 1.5231747404538287]

In [304]:
assertFloatList(answers['Q1'], 3) # Check the format of your answer (three floats)

In [305]:
### Question 2

In [306]:
def feature(datum):
    feat1 = datum['review_text'].count('!')
    feat2 = len(datum['review_text'])
    return [feat1]+[feat2]
    

In [307]:
X = [feature(data) for data in dataset]
Y = [data['rating'] for data in dataset]

In [308]:
X[:10]

[[0, 1326],
 [1, 224],
 [0, 118],
 [0, 1952],
 [0, 554],
 [0, 486],
 [4, 257],
 [2, 10],
 [1, 31],
 [0, 62]]

In [309]:
lr=LinearRegression()
lr.fit(X,Y)

LinearRegression()

In [311]:
theta0, [theta1, theta2]=lr.intercept_,lr.coef_
[theta0, theta1, theta2]

[3.7175128077972013, 0.07527591733232629, -4.121506529487976e-05]

In [312]:
Y_pre=lr.predict(X)
Y_pre

array([3.66286163, 3.78355655, 3.71264943, ..., 3.68338673, 3.7018923 ,
       3.7079097 ])

In [313]:
mse=mean_squared_error(Y,Y_pre)
mse

1.5214029246165832

In [315]:
answers['Q2'] = [theta0, theta1, theta2, mse]
print(answers["Q2"])

[3.7175128077972013, 0.07527591733232629, -4.121506529487976e-05, 1.5214029246165832]


In [316]:
assertFloatList(answers['Q2'], 4)

In [38]:
### Question 3

In [39]:
def feature(datum, deg):
    # feature for a specific polynomial degree
    feat = datum['review_text'].count('!')
    ans=[]
    ans.append(feat)
    for i in range(deg-1):
        tmp=ans[-1]
        ans.append(tmp*feat)
    return [1] + ans

In [40]:
#degree 1
X = [feature(data,1) for data in dataset]
Y = [data['rating'] for data in dataset]

In [41]:
X[:10]

[[1, 0],
 [1, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 4],
 [1, 2],
 [1, 1],
 [1, 0]]

In [42]:
lr=LinearRegression()
lr.fit(X,Y)
Y_pre=lr.predict(X)
mse=mean_squared_error(Y,Y_pre)
mse

1.5231747404538287

In [45]:
mses=[]

In [46]:
mses.append(mse)

In [49]:
#degree 2
X = [feature(data,2) for data in dataset]
lr=LinearRegression()
lr.fit(X,Y)
Y_pre=lr.predict(X)
mse=mean_squared_error(Y,Y_pre)
mse

1.5046686106250917

In [50]:
mses.append(mse)

In [51]:
#degree 3
X = [feature(data,3) for data in dataset]
lr=LinearRegression()
lr.fit(X,Y)
Y_pre=lr.predict(X)
mse=mean_squared_error(Y,Y_pre)
mse

1.496684551517923

In [52]:
mses.append(mse)

In [53]:
#degree 4
X = [feature(data,4) for data in dataset]
lr=LinearRegression()
lr.fit(X,Y)
Y_pre=lr.predict(X)
mse=mean_squared_error(Y,Y_pre)
mse

1.490447730223069

In [54]:
mses.append(mse)

In [55]:
#degree 5
X = [feature(data,5) for data in dataset]
lr=LinearRegression()
lr.fit(X,Y)
Y_pre=lr.predict(X)
mse=mean_squared_error(Y,Y_pre)
mse

1.4896106953961648

In [56]:
mses.append(mse)

In [65]:
print(mses)

[1.5231747404538287, 1.5046686106250917, 1.496684551517923, 1.490447730223069, 1.4896106953961648]


In [70]:
answers['Q3']=mses

In [71]:
assertFloatList(answers['Q3'], 5)# List of length 5

In [121]:
### Question 4

In [167]:
def feature(datum):
    # your implementation
    feat = datum['review_text'].count('!')
    return [1] + [feat]
X = [feature(data) for data in dataset]
Y = [data['rating'] for data in dataset]

In [168]:
X_train=X[:len(X)//2]
X_test=X[len(X)//2:]
Y_train=Y[:len(Y)//2]
Y_test=Y[len(Y)//2:]

In [170]:
#degree 1
lr=LinearRegression()
lr.fit(X_train,Y_train)
Y_pre=lr.predict(X_test)
mse=mean_squared_error(Y_test,Y_pre)
mse

1.5248743859866292

In [171]:
mses=[]
mses.append(mse)

In [172]:
def moredegree(data):
    for i in range(len(data)):
        tmp=data[i]+[data[i][1]*data[i][-1]]
        data[i]=tmp
    return data

In [173]:
#degree 2
X_train=moredegree(X_train)
X_test=moredegree(X_test)
lr.fit(X_train,Y_train)
Y_pre=lr.predict(X_test)
mse=mean_squared_error(Y_test,Y_pre)
mse

1.4977199259322445

In [174]:
mses.append(mse)

In [175]:
#degree 3
X_train=moredegree(X_train)
X_test=moredegree(X_test)
lr.fit(X_train,Y_train)
Y_pre=lr.predict(X_test)
mse=mean_squared_error(Y_test,Y_pre)
mse

1.4856632190311088

In [176]:
mses.append(mse)

In [177]:
#degree 4
X_train=moredegree(X_train)
X_test=moredegree(X_test)
lr.fit(X_train,Y_train)
Y_pre=lr.predict(X_test)
mse=mean_squared_error(Y_test,Y_pre)
mse

1.4767337440080983

In [178]:
mses.append(mse)

In [179]:
#degree 5
X_train=moredegree(X_train)
X_test=moredegree(X_test)
lr.fit(X_train,Y_train)
Y_pre=lr.predict(X_test)
mse=mean_squared_error(Y_test,Y_pre)
mse

1.4809577272893133

In [180]:
mses.append(mse)

In [181]:
mses

[1.5248743859866292,
 1.4977199259322445,
 1.4856632190311088,
 1.4767337440080983,
 1.4809577272893133]

In [182]:
answers['Q4'] = mses

In [183]:
assertFloatList(answers['Q4'], 5)

In [184]:
### Question 5

In [185]:
def median(arr):
    arr.sort()
    lenth=len(arr)
    return arr[lenth//2] if lenth%2==1 else (arr[lenth//2]+arr[lenth//2-1])/2

In [186]:
best_theta=median(Y_train)
best_theta

4.0

In [187]:
from sklearn.metrics import mean_absolute_error

In [188]:
mae=mean_absolute_error(Y_test,[best_theta]*len(Y_test))
mae

0.907

In [189]:
answers['Q5'] = mae

In [190]:
assertFloat(answers['Q5'])

In [534]:
### Question 6

In [535]:
f = open("beer_50000.json")
dataset = []
for l in f:
    if 'user/gender' in l:
        dataset.append(eval(l))

In [536]:
len(dataset)

20403

In [537]:
dataset[0]

{'review/appearance': 4.0,
 'beer/style': 'American Double / Imperial IPA',
 'review/palate': 4.0,
 'review/taste': 4.5,
 'beer/name': 'Cauldron DIPA',
 'review/timeUnix': 1293735206,
 'user/gender': 'Male',
 'user/birthdayRaw': 'Jun 16, 1901',
 'beer/ABV': 7.7,
 'beer/beerId': '64883',
 'user/birthdayUnix': -2163081600,
 'beer/brewerId': '1075',
 'review/timeStruct': {'isdst': 0,
  'mday': 30,
  'hour': 18,
  'min': 53,
  'sec': 26,
  'mon': 12,
  'year': 2010,
  'yday': 364,
  'wday': 3},
 'user/ageInSeconds': 3581417047,
 'review/overall': 4.0,
 'review/text': "According to the website, the style for the Caldera Cauldron changes every year. The current release is a DIPA, which frankly is the only cauldron I'm familiar with (it was an IPA/DIPA the last time I ordered a cauldron at the horsebrass several years back). In any event... at the Horse Brass yesterday.\t\tThe beer pours an orange copper color with good head retention and lacing. The nose is all hoppy IPA goodness, showcasing

In [538]:
def feature(datum):
    # your implementation
    feat = datum['review/text'].count('!')
    return [feat]

In [539]:
X = [[1]+feature(data) for data in dataset]
Y = [1 if data['user/gender']=='Female' else 0 for data in dataset]

In [540]:
print(X[:40])

[[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 1], [1, 1], [1, 0], [1, 1], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 2], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 3], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 1], [1, 0], [1, 0], [1, 0]]


In [541]:
print(Y[:40])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [542]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [543]:
Lr=LogisticRegression()
Lr.fit(X,Y)

LogisticRegression()

In [544]:
y_pre=Lr.predict(X)

In [545]:
coef_mat=confusion_matrix(Y,y_pre)
coef_mat

array([[20095,     0],
       [  308,     0]])

In [546]:
TN, FP=coef_mat[0][0],coef_mat[0][1]
FN, TP=coef_mat[1][0],coef_mat[1][1]

In [547]:
def get_ber(TP,TN,FP,FN):
    return (FP/(FP+TN)+FN/(FN+TP))/2

In [548]:
BER=get_ber(TP,TN,FP,FN)
BER

0.5

In [549]:
answers['Q6'] = [TP, TN, FP, FN, BER]
print(answers['Q6'])

[0, 20095, 0, 308, 0.5]


In [550]:
assertFloatList(answers['Q6'], 5)

In [551]:
### Question 7

In [552]:
X = [[1]+feature(data) for data in dataset]
Y = [data['user/gender']=='Female' for data in dataset]

In [553]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
Lr=LogisticRegression(class_weight='balanced')
Lr.fit(X,Y)
y_pre=Lr.predict(X)

In [554]:
y_pre=Lr.predict(X)
coef_mat=confusion_matrix(Y,y_pre)
coef_mat

array([[16332,  3763],
       [  220,    88]])

In [558]:
TN, FP=coef_mat[0][0],coef_mat[0][1]
FN, TP=coef_mat[1][0],coef_mat[1][1]

In [559]:
BER=get_ber(TP,TN,FP,FN)
BER

0.4507731134255145

In [560]:
answers["Q7"] = [TP, TN, FP, FN, BER]
print(answers["Q7"])

[88, 16332, 3763, 220, 0.4507731134255145]


In [501]:
assertFloatList(answers['Q7'], 5)

In [244]:
### Question 8

In [245]:
precisionList=[]

In [249]:
Lr.coef_

array([[-0.03667618,  0.18669959]])

In [253]:
import numpy as np

In [254]:
conf=[np.dot(Lr.coef_,x) for x in X]
conf

[array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([0.15002341]),
 array([0.15002341]),
 array([-0.03667618]),
 array([0.15002341]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([0.336723]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([0.52342259]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([0.15002341]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([-0.03667618]),
 array([0.15002341]

In [255]:
len(conf)

20403

In [256]:
sbf=list(zip(conf,Y))
sbf.sort(reverse=True)
sbf[:10]

[(array([4.07071482]), 0),
 (array([2.76381768]), 0),
 (array([2.76381768]), 0),
 (array([2.57711809]), 0),
 (array([2.57711809]), 0),
 (array([2.3904185]), 0),
 (array([2.20371891]), 0),
 (array([2.20371891]), 0),
 (array([2.20371891]), 0),
 (array([2.01701932]), 0)]

In [258]:
def get_pre_k(sbf,k):
    num=0
    for i in range(k):
        if sbf[i][1]==True:
            num+=1
    return num/k

In [259]:
for k in [1, 10, 100, 1000, 10000]:
    precisionList.append(get_pre_k(sbf,k))
precisionList

[0.0, 0.0, 0.03, 0.033, 0.0308]

In [260]:
answers['Q8'] = precisionList

In [261]:
assertFloatList(answers['Q8'], 5) #List of five floats

In [562]:
f = open("answers_hw1.txt", 'w') # Write your answers to a file
f.write(str(answers) + '\n')
f.close()